services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: weiclothe_iam
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "9090:8080" 
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: